name: 🪲 Bug Report
description: Reporte um bug
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher este relatório de bug!
        
  - type: input
    id: contact
    attributes:
      label: Detalhes de Contato
      description: Como podemos entrar em contato com você se precisarmos de mais informações? 
      placeholder: ex. email@example.com
    validations:
      required: false
    
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Descreva brevemente o problema aqui.
      placeholder: Nos diga o que você viu!
      value: "Um bug aconteceu!"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Seu ambiente.
      description: Descreva melhor o ambiente que você utilizou para reproduzir o problema.
      placeholder: (plataforma, sistema operacional, browser, etc.)
      render: shell      

  - type: markdown
    id: logs
    attributes:
      label: Como reproduzir o preblema?
      description: Descreva o passo-a-passo para reproduzir esse problema. Acrescente qualquer código relevante.
      render: shell
