name: 🚀 Feature request
description: Sugira uma funianalidade/ideia para este projeto
title: "[Feature Request / Suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Agradecemos o seu feedback sobre como melhorar este projeto. Certifique-se de incluir o máximo de detalhes e quaisquer recursos adicionais, se possível!
      
  - type: textarea
    id: problem
    attributes:
      label: Sua sugestão está relacionada com algum problema?
      description: Descreva de forma clara e concisa qual é esse problema.
      placeholder: Eu sempre fico frustrado quando [...]
    validations:
      required: true
      
  - type: textarea
    id: Suggestion
    attributes:
      label: Sugestão / Solicitação de Funcionalidade
      description: Descreva as funcionalidades que você gostaria de ver adicionados.
      placeholder: Nos diga suas sugestões!
      value: "Sua sugestão aqui"
    validations:
      required: true
 